- name: install mysql client.
    ansible.builtin.yum:
      name: mysql
      state: present
  
- name: Load Schema
    ansible.builtin.shell: "mysql -h mysql.robokart.online -uroot -pRoboShop@1 < /app/schema/{{componenet}}.sql"
      
- name: Restart the Service
    ansible.builtin.service:
      name: {{component}}
      state: restarted
      enabled: true