- name: install golang
  ansible.builtin.import_role:
    name: common
    tasks_from: setup-golang

- name: setup application
  ansible.builtin.import_role:
    name: common
    tasks_from: setup-app

- name: download the dependencies.
  ansible.builtin.command: "{{item}}"
  args: 
    chdir: /app
  loop:
  - go mod init dispatch
  - go get 
  - go build

- name: setup systemd.service
  ansible.builtin.import_role:
    name: common
    tasks_from: setup-systemd-service



