- name: Verify and add user if doesn't exist already
  ansible.builtin.command: id roboshop
  register: exitstatus
  ignore_errors: yes

- when: exitstatus.rc != 0
  name: add user
  ansible.builtin.user:
    name: roboshop

- name: verify and add /app directory if doesn't exist already
  ansible.builtin.stat:
    path: /app
  register: dirstatus
  ignore_errors: yes

- when: dirstatus.stat.exists == false
  name: add /app directory
  ansible.builtin.file:
    path: /app
    state: directory

 - name: Download the application code to created app directory.
   ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: "/tmp/{{component}}.zip"
    
- name: "unzipping {{component}}.zip"
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes